name: Security Gatekeeper Pipeline

on:
  push:
    branches: [ "main", "vulnerable" ]
  workflow_dispatch:

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t vulnerable-app:local .

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: vulnerable-app:local
          format: table
          exit-code: 1
          severity: CRITICAL
          ignore-unfixed: true
